set(_CATKIN_CURRENT_PACKAGE "pose_merger")
set(pose_merger_VERSION "0.0.0")
set(pose_merger_MAINTAINER "antbre <antbre@todo.todo>")
set(pose_merger_PACKAGE_FORMAT "2")
set(pose_merger_BUILD_DEPENDS )
set(pose_merger_BUILD_EXPORT_DEPENDS )
set(pose_merger_BUILDTOOL_DEPENDS "catkin")
set(pose_merger_BUILDTOOL_EXPORT_DEPENDS )
set(pose_merger_EXEC_DEPENDS )
set(pose_merger_RUN_DEPENDS )
set(pose_merger_TEST_DEPENDS )
set(pose_merger_DOC_DEPENDS )
set(pose_merger_URL_WEBSITE "")
set(pose_merger_URL_BUGTRACKER "")
set(pose_merger_URL_REPOSITORY "")
set(pose_merger_DEPRECATED "")