set(_CATKIN_CURRENT_PACKAGE "encoder_2_height")
set(encoder_2_height_VERSION "0.0.0")
set(encoder_2_height_MAINTAINER "antbre <antbre@todo.todo>")
set(encoder_2_height_PACKAGE_FORMAT "2")
set(encoder_2_height_BUILD_DEPENDS )
set(encoder_2_height_BUILD_EXPORT_DEPENDS )
set(encoder_2_height_BUILDTOOL_DEPENDS "catkin")
set(encoder_2_height_BUILDTOOL_EXPORT_DEPENDS )
set(encoder_2_height_EXEC_DEPENDS )
set(encoder_2_height_RUN_DEPENDS )
set(encoder_2_height_TEST_DEPENDS )
set(encoder_2_height_DOC_DEPENDS )
set(encoder_2_height_URL_WEBSITE "")
set(encoder_2_height_URL_BUGTRACKER "")
set(encoder_2_height_URL_REPOSITORY "")
set(encoder_2_height_DEPRECATED "")