set(_CATKIN_CURRENT_PACKAGE "file_writer")
set(file_writer_VERSION "0.0.0")
set(file_writer_MAINTAINER "antbre <antbre@todo.todo>")
set(file_writer_PACKAGE_FORMAT "2")
set(file_writer_BUILD_DEPENDS "message_generation" "message_runtime")
set(file_writer_BUILD_EXPORT_DEPENDS )
set(file_writer_BUILDTOOL_DEPENDS "catkin")
set(file_writer_BUILDTOOL_EXPORT_DEPENDS )
set(file_writer_EXEC_DEPENDS "message_runtime")
set(file_writer_RUN_DEPENDS "message_runtime")
set(file_writer_TEST_DEPENDS )
set(file_writer_DOC_DEPENDS )
set(file_writer_URL_WEBSITE "")
set(file_writer_URL_BUGTRACKER "")
set(file_writer_URL_REPOSITORY "")
set(file_writer_DEPRECATED "")