set(_CATKIN_CURRENT_PACKAGE "file_writer_on_rest")
set(file_writer_on_rest_VERSION "0.0.0")
set(file_writer_on_rest_MAINTAINER "antbre <antbre@todo.todo>")
set(file_writer_on_rest_PACKAGE_FORMAT "2")
set(file_writer_on_rest_BUILD_DEPENDS "message_runtime")
set(file_writer_on_rest_BUILD_EXPORT_DEPENDS )
set(file_writer_on_rest_BUILDTOOL_DEPENDS "catkin")
set(file_writer_on_rest_BUILDTOOL_EXPORT_DEPENDS )
set(file_writer_on_rest_EXEC_DEPENDS "message_runtime")
set(file_writer_on_rest_RUN_DEPENDS "message_runtime")
set(file_writer_on_rest_TEST_DEPENDS )
set(file_writer_on_rest_DOC_DEPENDS )
set(file_writer_on_rest_URL_WEBSITE "")
set(file_writer_on_rest_URL_BUGTRACKER "")
set(file_writer_on_rest_URL_REPOSITORY "")
set(file_writer_on_rest_DEPRECATED "")