set(_CATKIN_CURRENT_PACKAGE "livox_update_time")
set(livox_update_time_VERSION "0.0.0")
set(livox_update_time_MAINTAINER "fabi <fabi@todo.todo>")
set(livox_update_time_PACKAGE_FORMAT "2")
set(livox_update_time_BUILD_DEPENDS )
set(livox_update_time_BUILD_EXPORT_DEPENDS )
set(livox_update_time_BUILDTOOL_DEPENDS "catkin")
set(livox_update_time_BUILDTOOL_EXPORT_DEPENDS )
set(livox_update_time_EXEC_DEPENDS )
set(livox_update_time_RUN_DEPENDS )
set(livox_update_time_TEST_DEPENDS )
set(livox_update_time_DOC_DEPENDS )
set(livox_update_time_URL_WEBSITE "")
set(livox_update_time_URL_BUGTRACKER "")
set(livox_update_time_URL_REPOSITORY "")
set(livox_update_time_DEPRECATED "")